---
# yamllint disable rule:line-length
name: Release

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - main

permissions: read-all

jobs:
  Release:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: variant-inc/actions-setup@09b70ad2427d62fb15dad2fed65becd6f741514b # v2
      - name: Create Release Action
        uses: variant-inc/actions-collection/create-release-tag@a6850634fd3f70e3e771d6aa9ff8a6741119eac6 # v2
